
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    dev.bank: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yestoday?serverTimezone=Asia/Seoul
    username: root
    password: Abc1234!
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/test
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #  jpa:
  #    show-sql: true
  #    hibernate.hbm2ddl.auto: update
  ##    hibernate:
  ##        ddl-auto: create


#

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  http.cors.enabled: true
  http.cors.allow-origin: "*"

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK



